config/routes.rb
Monalisa::Application.routes.draw do

  # root page for the application
  root :to => "home#index"

  # home page routes
  # routes are not rails restful and are explicitly defined
  get 'home/index'              => 'home#index'
  get 'home/initialbilling'     => 'home#initial_billing',       :as => 'initial_billing'
  get 'home/initialbalance'     => 'home#initial_balance',       :as => 'initial_balance'
  get 'home/initsess/:id'       => 'home#session_initial_state', :as => 'initial_session'
  get 'home/sessions/:status'   => 'home#session_status',        :as => 'session_status'
  get 'home/badsession/:status' => 'home#bad_session',           :as => 'bad_session'
  get 'home/system/:context'    => 'home#system_stats',          :as => 'system_stats'

  # maintenance screens
  get 'maint/index'
  get 'maint/notyet'

  # user logging in/out, resetting pasword will be under /user
  devise_for :users

  resources :users do
    member do
      get 'password'          # form to change password
      put 'update_password'   # update action to save new password
    end
  end

  get  'groups/search' => 'groups#ajax_search', :as => 'search_group'
  post 'groups/search' => 'groups#ajax_search', :as => 'search_group'
  resources :groups do
    resources :notes
    resources :offices
    resources :rates
    resources :provider_insurances
    get "dataerror/index" => 'dataerror#index', :as => 'dataerror'
    member do
      # for the group to provider relationship
      get 'associate'
      get 'patient_associate'
    end
  end

  get  'providers/search' => 'providers#ajax_search', :as => 'search_provider'
  post 'providers/search' => 'providers#ajax_search', :as => 'search_provider'
  resources :providers do
    resources :notes
    resources :offices
    resources :rates
    resources :provider_insurances
    get "dataerror/index" => 'dataerror#index', :as => 'dataerror'
    member do
      # for the provider to group relationship
      get 'associate'
      get 'patient_associate'
    end
  end

  # ajax handling requests for patients - changing the diagnosis drop down box
  get  'patients/ajax_diagnosis'            => 'patients#ajax_diagnosis',    :as => 'patients_ajax_diagnosis'
  # for handling the subscriber address box, same as patient
  get  'patients/subscribers/ajax_addr' => 'subscribers#ajax_addr', :as => 'patient_subscribers_ajax_addr'
  get  'patients/subscribers/ajax_subscriber' => 'subscribers#ajax_subscriber', :as => 'patient_subscribers_ajax_subscriber'
  get  'patients/search' => 'patients#ajax_search', :as => 'search_patient'
  post 'patients/search' => 'patients#ajax_search', :as => 'search_patient'
  get  'patients/check_duplicate' => 'patients#ajax_check_duplicate', :as => 'check_duplicate_patient'
  # route for working with cpt codes between provider and patient
  resources :patients do
      resources :notes
      resources :subscribers
      resources :managed_cares
      resources :patient_injuries
      #need the routes for iprocedures and idiagnostics to allow for deletes to function
      resources :iprocedures,  :only => :destroy
      resources :idiagnostics, :only => :destroy
      get 'patients_providers/:provider_id/ajax_redraw'    => 'patients#ajax_redraw', :as => 'patients_providers_ajax_redraw'
      get 'patients_groups/:group_id/ajax_redraw'          => 'patients#ajax_redraw', :as => 'patients_groups_ajax_redraw'
      get 'patients_providers/:provider_id/ajax_procedure' => 'patients#patients_providers_ajax_procedure',  :as => 'patients_providers_ajax_procedure'
      get 'patients_groups/:group_id/ajax_procedure'       => 'patients#patients_groups_ajax_procedure',     :as => 'patients_groups_ajax_procedure'
      get "dataerror/index"                                => 'dataerror#index',      :as => 'dataerror'
      member do
          get 'group_associate'
          get 'provider_associate'
          put 'update_associate'
      end
  end


  # for the patient to group relationhsip
  get  'patients_groups/ajax'          => 'patients_groups#ajax_next_patient', :as => "patients_groups_ajax"
  post 'patients_groups/ajax'          => 'patients_groups#ajax_next_patient', :as => "patients_groups_ajax"
  get  'patients_groups/search'        => 'patients_groups#ajax_search',       :as => 'search_patients_groups'
  post 'patients_groups/search'        => 'patients_groups#ajax_search',       :as => 'search_patients_groups'
  get  'patients_groups/:id'           => 'patients_groups#index',             :as => "patients_groups"
  get  'patients_groups/patients/:id'  => 'patients_groups#patient_index',     :as => "patients_groups_patients"
  resources :patients_groups,      :except => [:index, :new, :create, :show] do
      resources :iprocedures,      :except => [:index, :edit, :update, :show]
      resources :idiagnostics,     :except => [:index, :edit, :update, :show]
      resources :subscriber_valids, :except => [:index, :show, :new]
      get 'subscriber_valids/:subscriber_id/new' => 'subscriber_valids#new',   :as => 'new_subscriber_valid'
  end

  # for the patient to provider relationhsip
  get  'patients_providers/ajax'          => 'patients_providers#ajax_next_patient', :as => "patients_providers_ajax"
  post 'patients_providers/ajax'          => 'patients_providers#ajax_next_patient', :as => "patients_providers_ajax"
  get  'patients_providers/search'        => 'patients_providers#ajax_search',       :as => 'search_patients_providers'
  post 'patients_providers/search'        => 'patients_providers#ajax_search',       :as => 'search_patients_providers'
  get  'patients_providers/:id'           => 'patients_providers#index',             :as => 'patients_providers'
  get  'patients_providers/patients/:id'  => 'patients_providers#patient_index',     :as => 'patients_providers_patients'
  resources :patients_providers,   :except => [:index, :new, :create, :show] do
      resources :iprocedures,      :except => [:index, :edit, :update, :show]
      resources :idiagnostics,     :except => [:index, :edit, :update, :show]
      resources :subscriber_valids, :except => [:index, :show, :new]
      get 'subscriber_valids/:subscriber_id/new' => 'subscriber_valids#new',   :as => 'new_subscriber_valid'
  end

  get 'insurance_sessions/ajax_group'   => 'insurance_sessions#ajax_group',   :as => 'insurance_sessions_ajax_group'
  get 'insurance_sessions/ajax_patient' => 'insurance_sessions#ajax_patient', :as => 'insurance_sessions_ajax_patient'
  get 'insurance_sessions/ajax_reset'   => 'insurance_sessions#ajax_reset',   :as => 'insurance_sessions_ajax_reset'
  # ajax handling requests for patients - changing the diagnosis drop down box
  get    'insurance_billings/ajax_diagnosis'  => 'insurance_billings#ajax_diagnosis', :as => 'insurance_billings_ajax_diagnosis'
  # for handling the diagnositc codes adding and deleting
  post   'insurance_billings/:insurance_billing_id/diag_create'        => 'insurance_billings#diagnostic_create', :as => 'insurance_billings_diag_create'
  delete 'insurance_billings/:insurance_billing_id/diag_delete/:id'    => 'insurance_billings#diagnostic_delete', :as => 'insurance_billings_diag_delete'
  get    'insurance_billings/:insurance_billing_id/ajax_procedure'     => 'insurance_billings#ajax_procedure',    :as => 'insurance_billings_ajax_procedure'

  get    'insurance_billings/:insurance_billing_id/dataerror'          => 'dataerror#insurance_billing_index',    :as => 'insurance_billing_dataerror'
  get    'insurance_billings/:insurance_billing_id/dataerror/override' => 'dataerror#insurance_billing_override', :as => 'insurance_billing_override'

  resources :insurance_sessions do
    resources :notes
    resources :insurance_billings, :except => [:show, :create, :edit] do
      resources :iprocedures
      get 'secondary' => 'insurance_billings#secondary'                   # create a secondary / tertiary claim
      get 'waive'     => 'insurance_billings#waive',    :as => 'waive'    # waive the balance due and close session
      get 'unwaive'   => 'insurance_billings#unwaive',  :as => 'unwaive'  # waive the balance due and close session
      get 'balance'   => 'insurance_billings#balance',  :as => 'balance'  # balance billing
      get 'cob'       => 'insurance_billings#cob',      :as => 'cob'      # coordination of benefits
    end
    # routes for handling the balance bill records for each session
    resources :balance_bill_sessions, :except => [:index, :show] do
      get 'ajax_details'  => 'balance_bill_sessions#ajax_detail',    :as => 'ajax_detail'
    end
    resources :balance_bill_details, :only => :destroy
  end
  get "insurance_session_errors/index/:id" => 'insurance_session_errors#index',     :as => 'insurance_session_errors'

  # routes for handling the processing of balance bills and payments
  resources :balance_bills do
    get 'dataerror' => 'dataerror#balance_bill_index', :as => 'dataerror'
    resources :balance_bill_payments, :except => [:index, :show, :destroy]
  end
  get "balance_bill/ajax_select"  => "balance_bills#ajax_select", :as => "balance_bills_ajax_select"

  # balance bill workflow controller
  get "balance_bill_workflow/:id/show"    => 'balance_bill_workflow#show',        :as => "balance_bill_workflow_show"
  get "balance_bill_workflow/:id/print"   => 'balance_bill_workflow#print',       :as => "balance_bill_workflow_print"
  get "balance_bill_workflow/:id/waive"   => 'balance_bill_workflow#waive',       :as => "balance_bill_workflow_waive"
  get "balance_bill_workflow/:id/revert"  => 'balance_bill_workflow#revert',      :as => "balance_bill_workflow_revert"
  get "balance_bill_workflow/:id/close"   => 'balance_bill_workflow#close',       :as => "balance_bill_workflow_close"

  get "balance_bill_history"              => 'balance_bill_history#index',        :as => "balance_bill_history"
  get "balance_bill_history/:id/patient"  => 'balance_bill_history#patient',      :as => "balance_bill_history_patient"

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_filter :authenticate_user!

  #
  # main landing page for application.  Users are redirected to login when first accessing the system
  # The main menu is displayed on this screen and the session variables are all reset to nil
  #
  def index
    authorize! :manage, :home
    reset_session

    # base system stats
    @base = Hash.new
    @base[:patients]  = Patient.count
    @base[:groups]    = Group.count
    @base[:providers] = Provider.count

    # session billing stats
    @claims = Hash.new
    #ins billing claims
    # claims in the initial state do not have a stand alone view in ins billing, processing or eob controllers.
    # the view for claims in initial state will be under the home controller, since this is the only controller utilizing the view
    @claims[:initiated]     = InsuranceBilling.initial.count
    @claims[:ready]         = InsuranceBilling.pending.count
    @claims[:processed]     = InsuranceBilling.processed.count
    @claims[:agedprocessed]  = InsuranceBilling.aged_between(15.days.ago, 29.days.ago).count
    @claims[:agedprocessed2] = InsuranceBilling.aged_between(30.days.ago, 44.days.ago).count
    @claims[:agedprocessed3] = InsuranceBilling.aged_processed(45.days.ago).count
    # posted and unassigned EOBs
    @claims[:assigned]      = Eob.assigned.count
    @claims[:unassigned]    = Eob.unassigned.count

    #balance billing stats
    @balance = Hash.new
    @balance[:not_sent]     = BalanceBill.without_status(:deleted, :archived).with_balance_status(:initiated, :ready).count
    @balance[:invoiced]     = BalanceBill.without_status(:deleted, :archived).with_balance_status(:patient_invoiced).count
    @balance[:over_due]     = BalanceBill.without_status(:deleted, :archived).with_balance_status(:first_notice, :second_notice, :third_notice).count
    @balance[:collections]  = BalanceBill.without_status(:deleted, :archived).with_balance_status(:collections).count
    @balance[:partial]      = BalanceBill.without_status(:deleted, :archived).with_balance_status(:patient_invoiced, :partial_payment, :first_notice, :second_notice, :third_notice, :collections).count
    @balance[:paid]         = BalanceBill.without_status(:deleted, :archived).with_balance_status(:paid_in_full).count

    #pull the session stats
    @session = Hash.new
    @session[:primary]       = InsuranceSession.primary.count
    @session[:secondary]     = InsuranceSession.secondary.count
    @session[:tertiary]      = InsuranceSession.tertiary.count
    @session[:other]         = InsuranceSession.other.count
    @session[:balancebill]   = InsuranceSession.balancebill.count
    @session[:no_claims]     = InsuranceSession.no_claims.count
    @session[:closed_claims] = InsuranceSession.closed_claims.count

    #grab the Providers birthdays
    arr = []
    (0..13).each{|i| arr << (Date.today+i.day).yday }
    @provider_birthday = Provider.birthday(arr)
    #@patient_birthday = Patient.birthday(arr)
    @managed_care_warning = ManagedCare.includes(:patient).warning


    respond_to do |format|
      format.html # index.html.erb
    end
  end

  #
  # view a simple listing of all claims in the initial state.  Each claim will link to the
  # insurance billing controller, so the claims can be viewed individually.
  #
  def initial_billing
    authorize! :manage, :home
    @claims = InsuranceBilling.initial
    @title = "Claims in Initiated State"

    respond_to do |format|
      format.html {render :layout => "application" }# initial_billing.html.erb
    end
  end


  # GET home/initsess/:id
  # sets the session variables to the patient context then redirects to the
  # index on ins billing.  Setting the context correctly ensure ins billing functions correctly
  def session_initial_state
    authorize! :manage, :home
    @insurance_session = InsuranceSession.find(params[:id])
    set_patient_session(@insurance_session.patient_id, @insurance_session.patient.patient_name)
    respond_to do |format|
      format.html {
        if @insurance_session.status == SessionFlow::BALANCE
          redirect_to edit_insurance_session_balance_bill_session_path(@insurance_session, @insurance_session.balance_bill_session)
        else
          redirect_to insurance_session_insurance_billings_path(@insurance_session)
        end
      }
    end
  end

  #
  # GET home/initial_balance
  # displays list of all balance bills in the initial state
  def initial_balance
    authorize! :manage, :home
    @balance_bill = BalanceBill.initial
    @title = "Balance Bills in Initiated State"

    respond_to do |format|
      format.html {render :layout => "application" }# initial_balance.html.erb
    end
  end


  # GET /home/session_status/:status
  # displays the sessions in a certain status state
  #
  def session_status
    authorize! :manage, :home
    @status =  params[:status].to_i
    @title = "Sessions with Status: " + SessionFlow.status(@status)
    case @status
      when SessionFlow::PRIMARY
        @sessions = InsuranceSession.primary
      when SessionFlow::SECONDARY
        @sessions = InsuranceSession.secondary
      when SessionFlow::TERTIARY
        @sessions = InsuranceSession.tertiary
      when SessionFlow::OTHER
        @sessions = InsuranceSession.other
      when SessionFlow::BALANCE
        @sessions = InsuranceSession.balancebill
      else
        @sessions = nil
    end

    respond_to do |format|
      format.html {render :layout => "application" }
    end
  end


  #
  # GET /home/badsession/:status
  #
  def bad_session
    authorize! :manage, :home
    @status = params[:status].to_i
    case @status
      when 100   # all claims / balanced bills closed for the session
        @title = "All claims & balance bills closed for session"
        @sessions = InsuranceSession.closed_claims
      when 200   # no claims and balance bills  for the session
        @title = "No claims or balance bills for session"
        @sessions = InsuranceSession.no_claims
    end

    respond_to do |format|
      format.html {render :layout => "application" }
    end
  end

  #
  # GET /home/system_stats/:context
  # resets the session variables before redirecting to the appropriate index screen
  # this reset protects against pepole hitting the back button to get back to the home page
  # by hitting the back button, the session variables maay be set, which can cause an issue
  def system_stats
    authorize! :manage, :home
    reset_session
    respond_to do |format|
      case params[:context].to_i
        when Selector::GROUP
          format.html {redirect_to groups_path}
        when Selector::PROVIDER
          format.html {redirect_to providers_path}
        when Selector::PATIENT
          format.html {redirect_to patients_path}
      end
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/bad_session.html.erb
<% if @sessions.count == 0 %>
	<p>There are no sessions currently in this state.</p> 
<% else %>
	<table>
		<tr>
			<th>Claim</th>
			<th>Bal Bill</th>
			<th>DOS</th>
			<th>Patient</th>
			<th>Provider</th>
			<th>Group</th>
		</tr>
		<% @sessions.each do |session| %>
			<tr>
				<td><%= link_to image_tag('new-button.png', :alt => 'New Claim', :title => 'New Claim', :border => 0, :width => 20, :height => 20), new_insurance_session_insurance_billing_path(session.id) %></td>
				<td><%= link_to image_tag('new-button.png', :alt => 'New Balance Bill', :title => 'New Balance Bill', :border => 0, :width => 20, :height => 20), new_insurance_session_balance_bill_session_path(session.id) %></td>
				<td><%= session.dos.strftime("%m/%d/%Y") if !session.dos.blank? %></td>
				<td><%= session.patient.patient_name if !session.patient_id.blank? %></td>
				<td><%= session.provider.provider_name if !session.provider_id.blank? %></td>
				<td><%= session.group.group_name if !session.group_id.blank? %></td>
			</tr>
		<% end %>
	</table>
<% end %>

app/views/home/index.html.erb
<div class='index'>
	<div class='left'>
		<h2>Claims Status:</h2>
		<%= link_to "Claims Initiated: #{@claims[:initiated]}", initial_billing_path %><br />
		<%= link_to "Claims Ready: #{@claims[:ready]}", processing_claim_ready_path %><br />
		<%= link_to "Claims Submitted: #{@claims[:processed]}", processing_claim_submitted_path %><br />
		<%= link_to "Claims Submitted 15-29 Days: #{@claims[:agedprocessed]}", processing_claim_submitted_path(:aged => 15, :aged2 => 29) %><br />
		<%= link_to "Claims Submitted 30-44 Days: #{@claims[:agedprocessed2]}", processing_claim_submitted_path(:aged => 30, :aged2 => 44) %><br />
		<%= link_to "Claims Submitted > 45 Days: #{@claims[:agedprocessed3]}", processing_claim_submitted_path(:aged => 45) %><br />
		<br />
		<h2>EOB Status:</h2>
		<%= link_to "Eob's Posted: #{@claims[:assigned]}", eobs_path %><br />
		<%= link_to "Unassigned EOB's #{@claims[:unassigned]}", eob_unassigned_path  %><br />
		<br />
		<h2>Balance Bills:</h2>
		<%= link_to "Ready: #{@balance[:not_sent]}", balance_bills_path %><br />
		<%= link_to "Invoiced: #{@balance[:invoiced]}", "" %><br />
		<%= link_to "Over Due: #{@balance[:over_due]}", "" %><br />
		Balance Due: <%= @balance[:partial] %> <br />
		Paid: <%= @balance[:paid] %><br />
		<h2>Open Sessions:</h2>
		<%= link_to "Primary: #{@session[:primary]}", session_status_path(:status => SessionFlow::PRIMARY) %><br />
		<%= link_to "Secondary: #{@session[:secondary]}", session_status_path(:status => SessionFlow::SECONDARY) %><br />
		<%= link_to "Tertiary: #{@session[:tertiary]}", session_status_path(:status => SessionFlow::TERTIARY) %><br />
		<%= link_to "Other:	#{@session[:other]}", session_status_path(:status => SessionFlow::OTHER) %><br />
		<%= link_to "Billing Entries: #{@session[:balancebill]}", session_status_path(:status => SessionFlow::BALANCE) %><br />
		<br />
		<% if @session[:closed_claims] != 0 %>
			<%= link_to "All Claims Closed: #{@session[:closed_claims]}", bad_session_path(:status => 100) %><br />
		<% end %>
		<% if @session[:no_claims] != 0 %>
			<%= link_to "No Claims for Session: #{@session[:no_claims]}", bad_session_path(:status => 200) %><br />
		<% end %>
	</div>
	<div class='right'>
		<h2>Birthday Reminders</h2>
		Birthdays within next 10 days:<%= @provider_birthday.count %><br />
		<b>Providers:</b>
		<table>
			<% if @provider_birthday.count == 0 %>
				<tr><td>None</td></tr>
			<% else %>
				<% @provider_birthday.each do |birth| %>
					<tr>
						<td><%= link_to birth.provider_name, provider_path(birth) %></td>
						<td><%= birth.dob.strftime("%m/%d") %></td>
					</tr>
				<% end %>
			<% end %>
		</table>
		<h2>Managed Care Warning</h2>
		<table>
			<% if @managed_care_warning.blank? %>
				<tr><td>None</td></tr>
			<% else %>
				<% @managed_care_warning.each do |mc| %>
				 	<% if !mc.cob %>
						<tr>
							<td><%= link_to mc.patient.patient_name,  patient_managed_care_path(mc.patient.id, mc.id) %></td>
							<td><%= (mc.authorized_sessions ? mc.authorized_sessions : 0) - mc.used_sessions %></td>
							<td><%= mc.end_date.strftime("%m/%d/%y") if mc.end_date %></td>
							<td><% if mc.provider %>
									<%= mc.provider.provider_name %>
								<% elsif mc.group %>
								    <%= mc.group.group_name %>
								<% else %>
									Provider/Group Not Selected
								<% end %>
							</td>
						</tr>
					<% end %>
				<% end %>
			<% end %>
		</table>
		<h2>General System Stats</h2>
		<%= link_to "Groups: #{@base[:groups]}", system_stats_path(Selector::GROUP) %><br />
		<%= link_to "Providers: #{@base[:providers]}", system_stats_path(Selector::PROVIDER) %><br />
		<%= link_to "Patients: #{@base[:patients]}", system_stats_path(Selector::PATIENT) %>	<br />
	</div>
</div>

app/views/home/initial_balance.html.erb
<table>
	<tr>
		<th></th>
		<th>DOS</th>
		<th>Patient</th>
		<th>Provider</th>
		<th>Group</th>
		<th>Amount</th>
	</tr>
	<% @balance_bill.each do |balance| %>
		<tr>
			<td><%= link_to image_tag('view-button.png', :alt => 'View Balance Bill', :title => 'View Balance Bill', :border => 0, :width => 20, :height => 20), 
			        initial_session_path(balance.insurance_session_id) %>
				<%= link_to image_tag('err-button.png', :alt => 'Balance Bill Errors', :title => 'Balance Bill Errors', :border => 0, :width => 20, :height => 20), 
				    balance_bill_dataerror_path(balance)  if balance.dataerror %>
			</td>
			<td><%= balance.insurance_session.dos.strftime("%m/%d/%Y") if !balance.insurance_session.dos.blank? %></td>
			<td><%= balance.patient.patient_name if !balance.patient_id.blank? %></td>
			<td><%= balance.provider.provider_name if !balance.provider_id.blank? %></td>
			<td><%= balance.group.group_name if !balance.group_id.blank? %></td>
			<td><%= number_to_currency(balance.total_invoiced_amount) %></td>
		</tr>
	<% end %>
</table>

app/views/home/initial_billing.html.erb
<%= provider_name = "" %>

<table>
	<tr>
	</tr>
	<% @claims.each do |claim| %>
	<% if claim.provider.provider_name != provider_name %>
  		</table><br />
		<h3>Provider: <%= provider_name = claim.provider.provider_name %></h3>
		<table>
			<tr>
				<th>Select</th>
				<th class='dos'>DOS</th>
				<th class='patient'>Patient</th>
				<th class='amount'>Amount</th>
				<th class='group'>Group</th>
			</tr>
		<% end %>

		<tr>
			<td><%= link_to image_tag('view-button.png', :alt => 'View Claim', :title => 'View Claim', :border => 0, :width => 20, :height => 20), 
			        initial_session_path(claim.insurance_session_id) %>
				<%= link_to image_tag('err-button.png', :alt => 'Claim Errors', :title => 'Claim Errors', :border => 0, :width => 20, :height => 20), 
				    insurance_billing_dataerror_path(claim)  if claim.dataerror %>
			</td>
			<td><%= claim.dos.strftime("%m/%d/%Y") if !claim.dos.blank? %></td>
			<td><%= claim.patient.patient_name if !claim.patient_id.blank? %></td>			
			<td><%= number_to_currency(claim.insurance_billed) %></td>
			<td><%= claim.group.group_name if !claim.group_id.blank? %></td>
		</tr>
	<% end %>
</table>

app/views/home/session_status.html.erb
<% if @sessions.count == 0 %>
	<p>There are no sessions currently in this state.</p> 
<% else %>
	<table>
		<tr>
			<th></th>
			<th>DOS</th>
			<th>Patient</th>
			<th>Provider</th>
			<th>Group</th>
		</tr>
		<% @sessions.each do |session| %>
			<tr>
				<td><%= link_to image_tag('view-button.png', :alt => 'View', :title => 'View', :border => 0, :width => 20, :height => 20), initial_session_path(session.id) %></td>
				<td><%= session.dos.strftime("%m/%d/%Y") if !session.dos.blank? %></td>
				<td><%= session.patient.patient_name if !session.patient_id.blank? %></td>
				<td><%= session.provider.provider_name if !session.provider_id.blank? %></td>
				<td><%= session.group.group_name if !session.group_id.blank? %></td>
			</tr>
		<% end %>
	</table>
<% end %>